version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: librarydb
    environment:
      POSTGRES_DB: librarydb
      POSTGRES_USER: libraryuser
      POSTGRES_PASSWORD: library123
    ports:
      - "5434:5432"
    volumes:
      - library_pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  library_pgdata:
